name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.9.1
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^17.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  drift_dev: ^2.31.0
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - .env
